version: "3.7"

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
  yesbot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
