version: "3.7"

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: ytf-database:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
