version: "3.7"

services:
  postgres:
    image: postgres:12.6
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  yesbot:
    image: ghcr.io/yes-theory-fam/yesbot-ts:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
