export const locations = [
  {
    location: "Airplane",
    roles: [
      "First Class Passenger",
      "Air Marshall",
      "Mechanic",
      "Economy Class Passenger",
      "Economy Class Passenger",
      "Stewardess",
      "Steward",
      "Co-Pilot",
      "Captain",
    ],
  },
  {
    location: "Bank",
    roles: [
      "Armored Car Driver",
      "Manager",
      "Consultant",
      "Consultant",
      "Customer",
      "Customer",
      "Robber",
      "Security Guard",
      "Teller",
    ],
  },
  {
    location: "Beach",
    roles: [
      "Beach Waitress",
      "Kite Surfer",
      "Lifeguard",
      "Thief",
      "Beach Goer",
      "Beach Goer",
      "Beach Goer",
      "Beach Photographer",
      "Ice Cream Truck Driver",
    ],
  },
  {
    location: "Broadway Theater",
    roles: [
      "Coat Check Lady",
      "Prompter",
      "Cashier",
      "Visitor",
      "Visitor",
      "Visitor",
      "Director",
      "Actor",
      "Crewman",
    ],
  },
  {
    location: "Casino",
    roles: [
      "Bartender",
      "Head Security Guard",
      "Bouncer",
      "Manager",
      "Hustler",
      "Dealer",
      "Gambler",
      "Gambler",
      "Gambler",
    ],
  },
  {
    location: "Cathedral",
    roles: [
      "Priest",
      "Beggar",
      "Sinner",
      "Parishioner",
      "Tourist",
      "Tourist",
      "Sponsor",
      "Choir Singer",
      "Choir Singer",
    ],
  },
  {
    location: "Circus Tent",
    roles: [
      "Acrobat",
      "Acrobat",
      "Animal Trainer",
      "Magician",
      "Visitor",
      "Fire Eater",
      "Clown",
      "Juggler",
      "Juggler",
    ],
  },
  {
    location: "Corporate Party",
    roles: [
      "Entertainer",
      "Manager",
      "Unwelcomed Guest",
      "Unwelcomed Guest",
      "Unwelcomed Guest",
      "Owner",
      "Secretary",
      "Accountant",
      "Delivery Boy",
    ],
  },
  {
    location: "Crusader Army",
    roles: [
      "Monk",
      "Imprisoned Arab",
      "Servant",
      "Servant",
      "Servant",
      "Bishop",
      "Squire",
      "Archer",
      "Knight",
    ],
  },
  {
    location: "Day Spa",
    roles: [
      "Customer",
      "Customer",
      "Customer",
      "Stylist",
      "Masseuse",
      "Manicurist",
      "Makeup Artist",
      "Dermatologist",
      "Beautician",
    ],
  },
  {
    location: "Embassy",
    roles: [
      "Security Guard",
      "Security Guard",
      "Secretary",
      "Ambassador",
      "Government Official",
      "Tourist",
      "Refugee",
      "Refugee",
      "Diplomat",
    ],
  },
  {
    location: "Hospital",
    roles: [
      "Nurse",
      "Nurse",
      "Doctor",
      "Anesthesiologist",
      "Intern",
      "Patient",
      "Patient",
      "Therapist",
      "Surgeon",
    ],
  },
  {
    location: "Hotel",
    roles: [
      "Doorman",
      "Security Guard",
      "Manager",
      "Housekeeper",
      "Customer",
      "Customer",
      "Customer",
      "Bartender",
      "Bellman",
    ],
  },
  {
    location: "Military Base",
    roles: [
      "Deserter",
      "Colonel",
      "Medic",
      "Soldier",
      "Soldier",
      "Sniper",
      "Sniper",
      "Officer",
      "Tank Engineer",
    ],
  },
  {
    location: "Movie Studio",
    roles: [
      "Stuntman",
      "Sound Engineer",
      "Cameraman",
      "Director",
      "Costume Artist",
      "Actor",
      "Actor",
      "Actor",
      "Producer",
    ],
  },
  {
    location: "Ocean Liner",
    roles: [
      "Rich Passenger",
      "Rich Passenger",
      "Rich Passenger",
      "Cook",
      "Captain",
      "Bartender",
      "Musician",
      "Waiter",
      "Mechanic",
    ],
  },
  {
    location: "Passenger Train",
    roles: [
      "Mechanic",
      "Border Patrol",
      "Train Attendant",
      "Passenger",
      "Passenger",
      "Passenger",
      "Restaurant Chef",
      "Engineer",
      "Stoker",
    ],
  },
  {
    location: "Pirate Ship",
    roles: [
      "Cook",
      "Sailor",
      "Sailor",
      "Slave",
      "Slave",
      "Cannoneer",
      "Bound Prisoner",
      "Cabin Boy",
      "Brave Captain",
    ],
  },
  {
    location: "Polar Station",
    roles: [
      "Medic",
      "Geologist",
      "Geologist",
      "Expedition Leader",
      "Biologist",
      "Biologist",
      "Radioman",
      "Hydrologist",
      "Meteorologist",
    ],
  },
  {
    location: "Police Station",
    roles: [
      "Detective",
      "Lawyer",
      "Journalist",
      "Criminalist",
      "Archivist",
      "Patrol Officer",
      "Patrol Officer",
      "Criminal",
      "Criminal",
    ],
  },
  {
    location: "Restaurant",
    roles: [
      "Musician",
      "Customer",
      "Customer",
      "Bouncer",
      "Hostess",
      "Head Chef",
      "Food Critic",
      "Waiter",
      "Waiter",
    ],
  },
  {
    location: "School",
    roles: [
      "Gym Teacher",
      "Student",
      "Student",
      "Student",
      "Principal",
      "Security Guard",
      "Janitor",
      "Lunch Lady",
      "Maintenance Man",
    ],
  },
  {
    location: "Service Station",
    roles: [
      "Manager",
      "Tire Specialist",
      "Biker",
      "Biker",
      "Car Owner",
      "Car Owner",
      "Car Wash Operator",
      "Electrician",
      "Auto Mechanic",
    ],
  },
  {
    location: "Space Station",
    roles: [
      "Engineer",
      "Alien",
      "Alien",
      "Space Tourist",
      "Pilot",
      "Pilot",
      "Commander",
      "Scientist",
      "Doctor",
    ],
  },
  {
    location: "Submarine",
    roles: [
      "Cook",
      "Commander",
      "Sonar Technician",
      "Electronics Technician",
      "Sailor",
      "Sailor",
      "Sailor",
      "Radioman",
      "Navigator",
    ],
  },
  {
    location: "Supermarket",
    roles: [
      "Customer",
      "Customer",
      "Customer",
      "Cashier",
      "Butcher",
      "Janitor",
      "Security Guard",
      "Food Sample Demonstrator",
      "Shelf Stocker",
    ],
  },
  {
    location: "University",
    roles: [
      "Graduate Student",
      "Professor",
      "Professor",
      "Dean",
      "Psychologist",
      "Maintenance Man",
      "Student",
      "Student",
      "Janitor",
    ],
  },
];
