name: Yarn Install
description: Installs and caches yarn dependencies

runs:
  using: "composite"
  steps:
    - name: 'Enable corepack'
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: 21

    # This step should prefer the cached dependencies and restore node_modules
    - name: Install dependencies
      shell: bash
      run: yarn --immutable
