export enum ChatNames {
  BOT_DEVELOPMENT = "bot-development",
  CHAT = "chat",
  CHAT_FIVE = "chat-v",
  CHAT_TOO = "chat-too",
  CODING = "coding",
  DAILY_CHALLENGE = "daily-challenge",
  FOURTH_CHAT = "4th-chat",
  INTRODUCTIONS = "introductions",
  LEARNING_SPANISH = "learning-spanish",
  SELF_DEVELOPMENT = "self-development",
  TRAVEL_APPROVALS = "travel-approvals",
  TRAVELING_TOGETHER = "traveling-together",
  UPDATES = "updates",
  VOICE_CHAT = "voice-chat",
  VOICE_CHAT_TWO = "voice-chat-2",
  YESTHEORY_DISCUSSION = "yestheory-discussions",
  YESTHEORY_POSTED = "yestheoryposted",
  PERMANENT_TESTING = "permanent-testing",
  BOT_COMMANDS = "bot-commands",
  WATCH_ME_WORK = "• 🔨 Watch Me Work",
  WATCH_ME_WORK_TOO = "• 🔨 Watch Me Work Too",
  PRODUCTIVITY = "• 💪 Productivity (Push2Talk)",
  VOICE_CHAT_WIP = "voice-chat-wip",
}
