export enum ChatNames {
  BOT_DEVELOPMENT = "bot-development",
  CHAT = "chat",
  CHAT_FIVE = "chat-v",
  CHAT_TOO = "chat-too",
  DAILY_CHALLENGE = "daily-challenge",
  FOURTH_CHAT = "4th-chat",
  LEARNING_SPANISH = "learning-spanish",
  SELF_DEVELOPMENT = "self-development",
  UPDATES = "updates",
  VOICE_CHAT = "voice-chat",
  VOICE_CHAT_TWO = "voice-chat-2",
  YESTHEORY_DISCUSSION = "yestheory-discussions",
  YESTHEORY_POSTED = "yestheoryposted",
  CODING = "coding",
  TRAVEL_APPROVALS = "travel-approvals",
  TRAVELING_TOGETHER = "traveling-together",
}
